name: Building docker images
on: [push]                                

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}                    
jobs:
  push-image-to-docker-hub:               
    runs-on: ubuntu-latest                
    steps:
    - uses: actions/checkout@v2           
    - name: docker login
      run: |                              
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Get current date              
      id: date
      run: echo "::set-output name=date::$(date -I)"
    - name: Build the Docker image        
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
